# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-02 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.CharField(max_length=500)),
                ('encrypted_text', models.CharField(max_length=500)),
                ('algorithm', models.CharField(max_length=50)),
            ],
        ),
    ]
