# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_Decryption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_text', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='encryptedtext',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
