# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-03 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_Decryption', '0002_auto_20230803_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedtext',
            name='algorithm',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decryptedtext',
            name='decrypted_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
