# Generated by Django 3.2.20 on 2023-08-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption_Decryption', '0003_auto_20230803_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptedtext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedtext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
